version: "3.9"
services:
  node-api:
    image: ghcr.io/edkel20/cicd-projet2/node-api:latest
  frontend:
    image: ghcr.io/edkel20/cicd-projet2/frontend:latest
  cypress:
    image: cypress/included
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    entrypoint: cypress run --config baseUrl=http://frontend --headless --browser chrome -C config.cypress.js
    depends_on:
      - frontend
      - node-api