name: 'Deployer sur le serveur cible'
description: 'Effectuer un déploiement sur le serveur cible'
inputs:
  vps_key:
    description: 'clé ssh pour le vps'
    required: true
  server_ip:
    description: 'adresse IP du serveur cible'
    required: true
  user_vps:
    description: 'user for ssh connexion vps'
    default: root
  token_github:
    description: 'token for github'
    required: true
runs:
  using: 'composite'
  steps:
    - name: deployer sur le serveur
      shell: bash
      run: |
        eval $(ssh-agent -s)
        ssh-add - <<< "${{ inputs.vps_key }}"
        mkdir -p ~/.ssh 
        ssh-keyscan -H ${{ inputs.server_ip }} >> ~/.ssh/known_hosts
        scp docker-compose.production.yml ${{ inputs.user_vps }}@${{ inputs.server_ip }}:/root/docker-compose.production.yml
        ssh ${{ inputs.user_vps }}@${{ inputs.server_ip }} "docker login ghcr.io -u ${{ github.actor }} -p ${{ inputs.token_github }}"
        ssh ${{ inputs.user_vps }}@${{ inputs.server_ip }} "docker compose -f /root/docker-compose.production.yml up -d --force-recreate"
