  name: CI/CD workflow
  on: push
  jobs:
    build-frontend-and-node-api:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          include:
            - context_name: ./frontend
              image_name: ghcr.io/edkel20/cicd-projet2/frontend
            - context_name: ./node-api
              image_name: ghcr.io/edkel20/cicd-projet2/node-api
      permissions:
        packages: write
      steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: set up docker buildx
          uses: docker/setup-buildx-action@v3
        - name: login to github container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: build and push
          uses: docker/build-push-action@v5
          with:
            context: ${{ matrix.context_name }}
            push: true
            tags: ${{ matrix.image_name }}:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max